INFO:__main__:Booting up the script
  0%|          | 0/12 [00:00<?, ?it/s]/home/ec2-user/autojobs/root/auto_scripts/letsrun_summarizer.py:65: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 65 of the file /home/ec2-user/autojobs/root/auto_scripts/letsrun_summarizer.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  soup = BeautifulSoup(resp)
/home/ec2-user/autojobs/root/auto_scripts/letsrun_summarizer.py:55: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 55 of the file /home/ec2-user/autojobs/root/auto_scripts/letsrun_summarizer.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  soup = BeautifulSoup(resp)
  0%|          | 0/12 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/autojobs/root/auto_scripts/letsrun_summarizer.py", line 139, in <module>
    log_today_summary()
  File "/home/ec2-user/autojobs/root/auto_scripts/letsrun_summarizer.py", line 128, in log_today_summary
    today_summaries = get_todays_summaries()
  File "/home/ec2-user/autojobs/root/auto_scripts/letsrun_summarizer.py", line 98, in get_todays_summaries
    result = summarize_thread_text(thread_title, thread_text)
  File "/home/ec2-user/autojobs/root/auto_scripts/letsrun_summarizer.py", line 85, in summarize_thread_text
    response = OpenAIAIAdaptor().generate_response(prompt, json_mode=True)
  File "/home/ec2-user/autojobs/root/meta/ai_services.py", line 40, in generate_response
    response = self.client.chat.completions.create(**params)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/openai/resources/chat/completions.py", line 663, in create
    return self._post(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/openai/_base_client.py", line 1200, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/ec2-user/.local/lib/python3.9/site-packages/openai/_base_client.py", line 889, in request
    return self._request(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/openai/_base_client.py", line 918, in _request
    response = self._client.send(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/home/ec2-user/.local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 103, in handle_request
    return self._connection.handle_request(request)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 133, in handle_request
    raise exc
  File "/home/ec2-user/.local/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 111, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 176, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 212, in _receive_event
    data = self._network_stream.read(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)
  File "/usr/lib64/python3.9/ssl.py", line 1260, in recv
    return self.read(buflen)
  File "/usr/lib64/python3.9/ssl.py", line 1135, in read
    return self._sslobj.read(len)
KeyboardInterrupt
INFO:__main__:Booting up the script
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/autojobs/root/auto_scripts/letsrun_summarizer.py", line 139, in <module>
    log_today_summary()
  File "/home/ec2-user/autojobs/root/auto_scripts/letsrun_summarizer.py", line 127, in log_today_summary
    collection = DatabaseConnector().get_collection(LETSRUN_COLLECTION_NAME)
  File "/home/ec2-user/autojobs/root/meta/database_connector.py", line 26, in get_collection
    client = self.get_client()
  File "/home/ec2-user/autojobs/root/meta/database_connector.py", line 16, in get_client
    f"mongodb+srv://{DATABASE_USERNAME}:"
TypeError: can only concatenate str (not "NoneType") to str
INFO:__main__:Booting up the script
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/autojobs/root/auto_scripts/letsrun_summarizer.py", line 139, in <module>
    log_today_summary()
  File "/home/ec2-user/autojobs/root/auto_scripts/letsrun_summarizer.py", line 127, in log_today_summary
    collection = DatabaseConnector().get_collection(LETSRUN_COLLECTION_NAME)
  File "/home/ec2-user/autojobs/root/meta/database_connector.py", line 26, in get_collection
    client = self.get_client()
  File "/home/ec2-user/autojobs/root/meta/database_connector.py", line 16, in get_client
    f"mongodb+srv://{DATABASE_USERNAME}:"
TypeError: can only concatenate str (not "NoneType") to str
INFO:__main__:Booting up the script
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/autojobs/root/auto_scripts/letsrun_summarizer.py", line 139, in <module>
    log_today_summary()
  File "/home/ec2-user/autojobs/root/auto_scripts/letsrun_summarizer.py", line 127, in log_today_summary
    collection = DatabaseConnector().get_collection(LETSRUN_COLLECTION_NAME)
  File "/home/ec2-user/autojobs/root/meta/database_connector.py", line 26, in get_collection
    client = self.get_client()
  File "/home/ec2-user/autojobs/root/meta/database_connector.py", line 16, in get_client
    f"mongodb+srv://{DATABASE_USERNAME}:"
TypeError: can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/autojobs/root/auto_scripts/letsrun_summarizer.py", line 136, in <module>
    log_today_summary()
  File "/home/ec2-user/autojobs/root/auto_scripts/letsrun_summarizer.py", line 124, in log_today_summary
    collection = DatabaseConnector().get_collection(LETSRUN_COLLECTION_NAME)
  File "/home/ec2-user/autojobs/root/meta/database_connector.py", line 26, in get_collection
    client = self.get_client()
  File "/home/ec2-user/autojobs/root/meta/database_connector.py", line 16, in get_client
    f"mongodb+srv://{DATABASE_USERNAME}:"
TypeError: can only concatenate str (not "NoneType") to str
  0%|          | 0/14 [00:00<?, ?it/s]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
  7%|▋         | 1/14 [00:10<02:17, 10.58s/it]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
 14%|█▍        | 2/14 [00:21<02:08, 10.67s/it]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
 21%|██▏       | 3/14 [00:28<01:40,  9.15s/it]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
 29%|██▊       | 4/14 [00:35<01:22,  8.23s/it]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
 36%|███▌      | 5/14 [00:47<01:27,  9.68s/it]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
 43%|████▎     | 6/14 [00:55<01:11,  8.94s/it]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
 50%|█████     | 7/14 [01:06<01:07,  9.61s/it]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
 57%|█████▋    | 8/14 [01:11<00:50,  8.36s/it]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
 64%|██████▍   | 9/14 [01:28<00:54, 10.81s/it]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
 71%|███████▏  | 10/14 [01:39<00:44, 11.13s/it]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
 79%|███████▊  | 11/14 [01:47<00:30, 10.18s/it]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
 86%|████████▌ | 12/14 [02:01<00:22, 11.16s/it]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
 93%|█████████▎| 13/14 [02:09<00:10, 10.21s/it]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
100%|██████████| 14/14 [02:16<00:00,  9.42s/it]100%|██████████| 14/14 [02:16<00:00,  9.78s/it]
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:__main__:SUCCESSFULLY INSERTED SUMMARY
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pymongo/srv_resolver.py", line 97, in _resolve_uri
    results = _resolve(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pymongo/srv_resolver.py", line 45, in _resolve
    return resolver.resolve(*args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/dns/resolver.py", line 1565, in resolve
    return get_default_resolver().resolve(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/dns/resolver.py", line 1318, in resolve
    (nameserver, tcp, backoff) = resolution.next_nameserver()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/dns/resolver.py", line 763, in next_nameserver
    raise NoNameservers(request=self.request, errors=self.errors)
dns.resolver.NoNameservers: All nameservers failed to answer the query _mongodb._tcp.track_athletes.tqfgaze.mongodb.net. IN SRV: Server Do53:172.31.0.2@53 answered [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/autojobs/root/auto_scripts/letsrun_summarizer.py", line 136, in <module>
    log_today_summary()
  File "/home/ec2-user/autojobs/root/auto_scripts/letsrun_summarizer.py", line 124, in log_today_summary
    collection = DatabaseConnector().get_collection(LETSRUN_COLLECTION_NAME)
  File "/home/ec2-user/autojobs/root/meta/database_connector.py", line 26, in get_collection
    client = self.get_client()
  File "/home/ec2-user/autojobs/root/meta/database_connector.py", line 15, in get_client
    client = pymongo.MongoClient(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 766, in __init__
    res = uri_parser.parse_uri(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pymongo/uri_parser.py", line 556, in parse_uri
    nodes = dns_resolver.get_hosts()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pymongo/srv_resolver.py", line 131, in get_hosts
    _, nodes = self._get_srv_response_and_hosts(True)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pymongo/srv_resolver.py", line 111, in _get_srv_response_and_hosts
    results = self._resolve_uri(encapsulate_errors)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pymongo/srv_resolver.py", line 105, in _resolve_uri
    raise ConfigurationError(str(exc))
pymongo.errors.ConfigurationError: All nameservers failed to answer the query _mongodb._tcp.track_athletes.tqfgaze.mongodb.net. IN SRV: Server Do53:172.31.0.2@53 answered [Errno 101] Network is unreachable
  0%|          | 0/8 [00:00<?, ?it/s]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
 12%|█▎        | 1/8 [00:10<01:16, 10.96s/it]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
 25%|██▌       | 2/8 [00:20<01:02, 10.36s/it]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
 38%|███▊      | 3/8 [00:31<00:52, 10.60s/it]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
 50%|█████     | 4/8 [00:53<01:00, 15.08s/it]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
 62%|██████▎   | 5/8 [01:05<00:41, 13.83s/it]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
 75%|███████▌  | 6/8 [01:16<00:25, 12.95s/it]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
 88%|████████▊ | 7/8 [01:38<00:16, 16.03s/it]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
100%|██████████| 8/8 [01:48<00:00, 13.81s/it]100%|██████████| 8/8 [01:48<00:00, 13.50s/it]
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:__main__:SUCCESSFULLY INSERTED SUMMARY
