0it [00:00, ?it/s]1it [00:00,  3.35it/s]4it [00:12,  3.29s/it]5it [00:22,  5.25s/it]5it [00:22,  4.51s/it]
likely key error on summary for document so passing
likely key error on summary for document so passing
likely key error on summary for document so passing
got summary, now updating
got summary, now updating
0it [00:00, ?it/s]1it [00:00,  2.92it/s]4it [00:06,  1.70s/it]5it [00:14,  3.35s/it]5it [00:14,  2.80s/it]
likely key error on summary for document so passing
likely key error on summary for document so passing
likely key error on summary for document so passing
got summary, now updating
got summary, now updating
0it [00:00, ?it/s]1it [00:00,  3.33it/s]4it [00:06,  1.72s/it]4it [00:06,  1.62s/it]
likely key error on summary for document so passing
likely key error on summary for document so passing
likely key error on summary for document so passing
got summary, now updating
0it [00:00, ?it/s]1it [00:00,  3.21it/s]4it [00:10,  2.88s/it]5it [00:21,  5.01s/it]5it [00:21,  4.26s/it]
likely key error on summary for document so passing
likely key error on summary for document so passing
likely key error on summary for document so passing
got summary, now updating
got summary, now updating
0it [00:00, ?it/s]1it [00:00,  3.19it/s]4it [00:07,  2.01s/it]5it [00:17,  4.17s/it]5it [00:17,  3.46s/it]
likely key error on summary for document so passing
likely key error on summary for document so passing
likely key error on summary for document so passing
got summary, now updating
got summary, now updating
0it [00:00, ?it/s]1it [00:00,  3.16it/s]4it [00:05,  1.35s/it]4it [00:05,  1.28s/it]
likely key error on summary for document so passing
likely key error on summary for document so passing
likely key error on summary for document so passing
got summary, now updating
0it [00:00, ?it/s]1it [00:00,  3.26it/s]4it [00:06,  1.73s/it]4it [00:06,  1.62s/it]
likely key error on summary for document so passing
likely key error on summary for document so passing
likely key error on summary for document so passing
got summary, now updating
0it [00:00, ?it/s]ERROR:root:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.18it/s]ERROR:root:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:root:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:12,  3.40s/it]4it [00:12,  3.17s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  2.85it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:07,  2.02s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:17,  4.28s/it]INFO:__main__:got summary, now updating 

 =====
6it [00:28,  6.07s/it]6it [00:28,  4.71s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.08it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:11,  3.07s/it]4it [00:11,  2.86s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.22it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:06,  1.78s/it]4it [00:06,  1.67s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.27it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:06,  1.79s/it]4it [00:06,  1.68s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.18it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:09,  2.44s/it]4it [00:09,  2.28s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.01it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:12,  3.22s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:23,  5.44s/it]5it [00:23,  4.64s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  2.92it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:06,  1.72s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:11,  2.77s/it]INFO:__main__:got summary, now updating 

 =====
6it [00:20,  4.32s/it]6it [00:20,  3.36s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.22it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:08,  2.22s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:22,  5.63s/it]5it [00:22,  4.56s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.22it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:09,  2.58s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:19,  4.73s/it]5it [00:19,  3.99s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.06it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:14,  3.93s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:23,  5.17s/it]5it [00:23,  4.61s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.14it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:08,  2.27s/it]4it [00:08,  2.12s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.10it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:11,  2.96s/it]4it [00:11,  2.76s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.00it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:10,  2.78s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:18,  4.18s/it]5it [00:18,  3.64s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.13it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.38it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.20it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:12,  3.26s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:21,  5.00s/it]5it [00:21,  4.33s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  2.89it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:16,  4.43s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:31,  7.28s/it]INFO:__main__:got summary, now updating 

 =====
6it [00:39,  7.68s/it]6it [00:39,  6.64s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.28it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:06,  1.73s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:11,  2.61s/it]5it [00:11,  2.28s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.28it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:11,  3.13s/it]4it [00:11,  2.92s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.20it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:06,  1.71s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:12,  3.05s/it]5it [00:12,  2.59s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.08it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:06,  1.86s/it]4it [00:06,  1.74s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  2.98it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:11,  3.19s/it]4it [00:11,  2.98s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.09it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:04,  1.09s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:14,  3.55s/it]5it [00:14,  2.81s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.21it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:19,  5.13s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:28,  6.25s/it]5it [00:28,  5.64s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.16it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:05,  1.42s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:16,  4.20s/it]5it [00:16,  3.35s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.05it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:06,  1.77s/it]4it [00:06,  1.66s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  2.81it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:07,  2.02s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:17,  4.16s/it]INFO:__main__:got summary, now updating 

 =====
6it [00:23,  4.88s/it]6it [00:23,  4.00s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.35it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:10,  2.79s/it]4it [00:10,  2.60s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  2.83it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:07,  2.06s/it]4it [00:07,  1.93s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.35it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:08,  2.14s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:15,  3.55s/it]5it [00:15,  3.04s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  2.66it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:05,  1.57s/it]4it [00:05,  1.48s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.27it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.79it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.03it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:07,  2.11s/it]4it [00:07,  1.97s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.19it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.55it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.25it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:17,  4.62s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:25,  5.56s/it]5it [00:25,  5.04s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.16it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:10,  2.92s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:18,  4.20s/it]5it [00:18,  3.68s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.04it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:09,  2.49s/it]4it [00:09,  2.32s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  2.88it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:11,  3.17s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:36,  9.28s/it]INFO:__main__:got summary, now updating 

 =====
6it [00:54, 11.75s/it]6it [00:54,  9.15s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.21it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:11,  3.21s/it]4it [00:11,  2.99s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.03it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:14,  3.92s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:22,  5.09s/it]5it [00:22,  4.55s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.14it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:05,  1.56s/it]4it [00:05,  1.46s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.20it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:05,  1.51s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:12,  2.94s/it]INFO:__main__:got summary, now updating 

 =====
6it [00:21,  4.66s/it]6it [00:21,  3.55s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.26it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:05,  1.43s/it]4it [00:05,  1.35s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.17it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:07,  2.02s/it]4it [00:07,  1.89s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.13it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.39it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.17it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:08,  2.30s/it]4it [00:08,  2.15s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.18it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:12,  3.22s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:18,  4.04s/it]INFO:__main__:got summary, now updating 

 =====
6it [00:32,  6.88s/it]6it [00:32,  5.36s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  2.85it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:11,  3.15s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:27,  6.74s/it]5it [00:27,  5.56s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.08it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:10,  2.87s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:18,  4.19s/it]5it [00:18,  3.66s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.13it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:06,  1.70s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:11,  2.72s/it]5it [00:11,  2.35s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.11it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:12,  3.28s/it]4it [00:12,  3.06s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.10it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:06,  1.69s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:11,  2.70s/it]5it [00:11,  2.33s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.03it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:06,  1.72s/it]4it [00:06,  1.62s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.20it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:08,  2.21s/it]4it [00:08,  2.07s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  2.91it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:08,  2.20s/it]INFO:__main__:got summary, now updating 

 =====
5it [00:17,  4.15s/it]5it [00:17,  3.49s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.12it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:08,  2.33s/it]4it [00:08,  2.18s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  2.97it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
INFO:__main__:got summary, now updating 

 =====
4it [00:11,  3.18s/it]4it [00:11,  2.97s/it]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.05it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.14it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  2.96it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  8.87it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.16it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.46it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.06it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.17it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.24it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.70it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.27it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.79it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.06it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.17it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.17it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.50it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.10it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.27it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.03it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.09it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.10it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.29it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.48it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00, 10.41it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.37it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00, 10.10it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.00it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.00it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.04it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.12it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.18it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.54it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.11it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.32it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.02it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.06it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.31it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.93it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.11it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.33it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.02it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.06it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.33it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.98it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  2.97it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  8.91it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.08it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.23it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  2.92it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  8.76it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.16it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.45it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.16it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.48it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.09it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.24it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.24it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.71it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.02it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.05it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.27it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.79it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.10it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.30it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.20it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.58it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.10it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.29it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.00it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  8.98it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.02it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.04it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.13it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.39it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.25it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.73it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.00it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.00it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.00it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  8.98it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.14it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.40it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.12it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.36it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.27it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.81it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.24it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.70it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.30it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.90it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.10it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.29it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.27it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.80it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.03it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.07it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.24it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.72it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  2.94it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  8.82it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.10it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.30it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  2.94it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  8.81it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.18it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.53it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.13it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.37it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  2.82it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  8.46it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.15it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.43it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.08it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.22it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.11it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.33it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.13it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.39it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  2.95it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  8.84it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  2.95it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  8.84it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.07it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.19it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.01it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.02it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.25it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.75it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  2.95it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  8.83it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.21it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.60it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.15it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.45it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.12it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.34it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.09it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.27it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  2.97it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  8.90it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.08it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.24it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.16it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.46it/s]
0it [00:00, ?it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
1it [00:00,  3.26it/s]ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
ERROR:__main__:An exception occurred: 'summary'
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/scan_summary.py", line 31, in <module>
    prompt = "Can you summarize who this athlete is? \n\nContext:\n" + document["summary"]
KeyError: 'summary'
3it [00:00,  9.77it/s]
