Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/update_embeddings.py", line 5, in <module>
    import pinecone
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pinecone/__init__.py", line 11, in <module>
    from .core.grpc.index_grpc import *
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pinecone/core/grpc/index_grpc.py", line 23, in <module>
    from pinecone.core.grpc.protos.vector_service_pb2 import Vector as GRPCVector, \
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pinecone/core/grpc/protos/vector_service_pb2.py", line 21, in <module>
    from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2
  File "/home/ec2-user/.local/lib/python3.9/site-packages/protoc_gen_openapiv2/options/annotations_pb2.py", line 15, in <module>
    from protoc_gen_openapiv2.options import openapiv2_pb2 as protoc__gen__openapiv2_dot_options_dot_openapiv2__pb2
  File "/home/ec2-user/.local/lib/python3.9/site-packages/protoc_gen_openapiv2/options/openapiv2_pb2.py", line 35, in <module>
    _descriptor.EnumValueDescriptor(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 789, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/update_embeddings.py", line 5, in <module>
    import pinecone
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pinecone/__init__.py", line 11, in <module>
    from .core.grpc.index_grpc import *
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pinecone/core/grpc/index_grpc.py", line 23, in <module>
    from pinecone.core.grpc.protos.vector_service_pb2 import Vector as GRPCVector, \
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pinecone/core/grpc/protos/vector_service_pb2.py", line 21, in <module>
    from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2
  File "/home/ec2-user/.local/lib/python3.9/site-packages/protoc_gen_openapiv2/options/annotations_pb2.py", line 15, in <module>
    from protoc_gen_openapiv2.options import openapiv2_pb2 as protoc__gen__openapiv2_dot_options_dot_openapiv2__pb2
  File "/home/ec2-user/.local/lib/python3.9/site-packages/protoc_gen_openapiv2/options/openapiv2_pb2.py", line 35, in <module>
    _descriptor.EnumValueDescriptor(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 789, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/update_embeddings.py", line 5, in <module>
    import pinecone
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pinecone/__init__.py", line 11, in <module>
    from .core.grpc.index_grpc import *
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pinecone/core/grpc/index_grpc.py", line 23, in <module>
    from pinecone.core.grpc.protos.vector_service_pb2 import Vector as GRPCVector, \
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pinecone/core/grpc/protos/vector_service_pb2.py", line 21, in <module>
    from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2
  File "/home/ec2-user/.local/lib/python3.9/site-packages/protoc_gen_openapiv2/options/annotations_pb2.py", line 15, in <module>
    from protoc_gen_openapiv2.options import openapiv2_pb2 as protoc__gen__openapiv2_dot_options_dot_openapiv2__pb2
  File "/home/ec2-user/.local/lib/python3.9/site-packages/protoc_gen_openapiv2/options/openapiv2_pb2.py", line 35, in <module>
    _descriptor.EnumValueDescriptor(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 789, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Traceback (most recent call last):
  File "/home/ec2-user/autojobs/auto_scripts/update_embeddings.py", line 5, in <module>
    import pinecone
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pinecone/__init__.py", line 11, in <module>
    from .core.grpc.index_grpc import *
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pinecone/core/grpc/index_grpc.py", line 23, in <module>
    from pinecone.core.grpc.protos.vector_service_pb2 import Vector as GRPCVector, \
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pinecone/core/grpc/protos/vector_service_pb2.py", line 21, in <module>
    from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2
  File "/home/ec2-user/.local/lib/python3.9/site-packages/protoc_gen_openapiv2/options/annotations_pb2.py", line 15, in <module>
    from protoc_gen_openapiv2.options import openapiv2_pb2 as protoc__gen__openapiv2_dot_options_dot_openapiv2__pb2
  File "/home/ec2-user/.local/lib/python3.9/site-packages/protoc_gen_openapiv2/options/openapiv2_pb2.py", line 35, in <module>
    _descriptor.EnumValueDescriptor(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 789, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
